name: Format and Commit

on:
  push:
    branches: [ "main" ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Important: 'ref' ensures we push back to the right place
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fix Formatting
        run: npx prettier --write "**.html" "**.css"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix formatting with Prettier"